[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/mosaic-pixel",
]
exclude = [
    "projects/.DS_Store",
    "projects/mosaic-wolfram",
]

[profile.release]
lto = true
